/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "CustomWidget_MVC", Title = "CustomWidget", SectionName = "CustomWidgets")]
	public class CustomWidgetController : Controller, IPersonalizable
	{
		// GET: CustomWidget
		public ActionResult Index()
		{
			var model = new CustomWidgetModel();
			model.Message = this.Message;
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}